export const API_ROOT = 'http://localhost:8080/api';
export const API_TOKEN = 'http://localhost:8080/api/login';
export const ROOT = 'http://localhost:8080';

export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE'

}

export const userConstants = {
  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

  GET_ALL_USERS_REQUEST: 'GET_ALL_USERS_REQUEST',
  GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
  GET_ALL_USERS_FAILURE: 'GET_ALL_USERS_FAILURE',
}
export const brandConstants = {
  GET_ALL_BRAND_SUCCESS: 'GET_ALL_BRAND_SUCCESS',
}

export const medicalConstants = {
  GET_ALL_MEDICAL_REQUEST: 'GET_ALL_MEDICAL_REQUEST',
}